AcsEmulator/AcsEmulatorAPI/Identity.cs
AcsEmulator/AcsEmulatorAPI/Properties/launchSettings.json
TestClients/js/.gitignore
TestClients/js/identity/.env
TestClients/js/identity/README.md
TestClients/js/identity/package-lock.json
TestClients/js/identity/package.json
TestClients/js/identity/src/issueToken.ts
TestClients/js/identity/src/revokeTokens.ts
TestClients/js/identity/tsconfig.json

had to change to use http instead of https
for some reason the client gets a 400 response

copy over js sdk identity samples and point toward localhost

---

AcsEmulator/AcsEmulatorAPI/AcsEmulatorAPI.csproj
AcsEmulator/AcsEmulatorAPI/Chat.cs
AcsEmulator/AcsEmulatorAPI/Identity.cs
AcsEmulator/AcsEmulatorAPI/Models/User.cs
AcsEmulator/AcsEmulatorAPI/Properties/launchSettings.json
AcsEmulator/AcsEmulatorAPI/UserToken.cs
AcsEmulator/AcsEmulatorAPI/appsettings.json
TestClients/js/chat/.env
TestClients/js/chat/README.md
TestClients/js/chat/package-lock.json
TestClients/js/chat/package.json
TestClients/js/chat/src/messageOperations.ts
TestClients/js/chat/src/participantsOperations.ts
TestClients/js/chat/src/threadOperations.ts
TestClients/js/chat/tsconfig.json
TestClients/js/identity/.env

I'm running into issues because Azure Core's auth policy doesn't allow setting Bearer over http. Python SDK has a way to turn that check off, JS has something with tlsOptions to theoretically support self-signed certs but I couldn't get it to work

generate jwt token

---

AcsEmulator/AcsEmulatorAPI/Models/ChatThread.cs
AcsEmulator/AcsEmulatorAPI/Program.cs
TestClients/js/ui/index.html

It's doing something at least :-)

use chat bundles in pure html+js and enable cors

---

AcsEmulator/AcsEmulatorAPI/Chat.cs
AcsEmulator/AcsEmulatorAPI/Migrations/20220922130122_AddChatMessage.Designer.cs
AcsEmulator/AcsEmulatorAPI/Migrations/20220922130122_AddChatMessage.cs
AcsEmulator/AcsEmulatorAPI/Migrations/20220922132629_AddChatMessageSender.Designer.cs
AcsEmulator/AcsEmulatorAPI/Migrations/20220922132629_AddChatMessageSender.cs
AcsEmulator/AcsEmulatorAPI/Models/ChatMessage.cs
AcsEmulator/AcsEmulatorAPI/Models/ChatModels.cs
AcsEmulator/AcsEmulatorAPI/Models/ChatThread.cs

Chat controller now needs some refactoring...
I might not be a user in the thread, but I can send messages now!
And they are getting persisted!
```shell
SQLite version 3.39.3 2022-09-05 11:02:23
Enter ".help" for usage hints.
sqlite> select * from ChatThreads;
19:f1a8c76b-7dea-4bf9-b331-51aa5c99c954|8:acs:d9b2f18a-2c34-415e-889d-c210cb738186_adee031c-3d3f-4cfe-909b-84d7369bbb2d|2022-09-22 13:47:10.073021+00:00|The weather forecast ??????
19:5c0edc91-25c6-476d-95d5-f82de3edb100|8:acs:d9b2f18a-2c34-415e-889d-c210cb738186_adee031c-3d3f-4cfe-909b-84d7369bbb2d|2022-09-22 13:47:19.3891916+00:00|My topic
sqlite> select * from ChatMessages;
EFECECAD-C99C-4083-9039-54412F985793|19:f1a8c76b-7dea-4bf9-b331-51aa5c99c954|Hello|Emil the Emulator|8:acs:d9b2f18a-2c34-415e-889d-c210cb738186_adee031c-3d3f-4 …
```

Added GET and POST for /messages

---

AcsEmulator/AcsEmulatorAPI/ChatController.cs
AcsEmulator/AcsEmulatorAPI/Models/ChatThread.cs
TestClients/js/ui/ui.js

only list chat threads that the caller is part of

---

AcsEmulator/AcsEmulatorAPI/ChatController.cs

Fixes the "you are not in this thread" error.

Add GET route for individual threads

---

AcsEmulator/acs-emulator-ui/src/App.tsx
AcsEmulator/acs-emulator-ui/src/components/Quickstart.tsx

Add basic Quickstart page UI with info

---

AcsEmulator/acs-emulator-ui/package-lock.json
AcsEmulator/acs-emulator-ui/package.json
AcsEmulator/acs-emulator-ui/src/App.tsx
AcsEmulator/acs-emulator-ui/src/components/Identities.tsx
AcsEmulator/acs-emulator-ui/src/services/identity.ts

Add basic identities page

---

AcsEmulator/AcsEmulatorAPI/ChatController.cs
AcsEmulator/acs-emulator-ui/package-lock.json
AcsEmulator/acs-emulator-ui/package.json
AcsEmulator/acs-emulator-ui/src/App.tsx
AcsEmulator/acs-emulator-ui/src/components/ChatThreads.tsx
AcsEmulator/acs-emulator-ui/src/components/Identities.tsx
AcsEmulator/acs-emulator-ui/src/services/chatThread.ts

Add basic chat thread UI and "admin" API to get all threads for all users

---

AcsEmulator/AcsEmulatorAPI/ChatThreadController.cs
AcsEmulator/AcsEmulatorAPI/Models/ChatModels.cs
AcsEmulator/AcsEmulatorAPI/Trouter.cs

Unfortunately, the Chat composite doesn't seem to send the senderDisplayName, at least when used from within the storybook (?)

Add typing notifications POST route and websocket messages

---

AcsEmulator/AcsEmulatorAPI/AcsEmulatorAPI.csproj
AcsEmulator/AcsEmulatorAPI/Email.cs
AcsEmulator/AcsEmulatorAPI/Program.cs

This is the latest API proposal which hasn't been deployed yet and doesn't have a SDK.
Next todo is to store emails in the db

Add Emails API mock

---

AcsEmulator/AcsEmulatorAPI/Program.cs
AcsEmulator/AcsEmulatorAPI/Sms.cs

Todo: DB entity + save messages to DB.

Mock SMS api

---

AcsEmulator/AcsEmulatorAPI/Sms.cs
AcsEmulator/acs-emulator-ui/src/App.tsx
AcsEmulator/acs-emulator-ui/src/components/LeftNav.tsx
AcsEmulator/acs-emulator-ui/src/components/SmsMessages.tsx
AcsEmulator/acs-emulator-ui/src/services/sms.ts

Will merge this after #40 
Basic UI:

Add basic UI to display SMS

---

AcsEmulator/AcsEmulatorAPI/Email.cs
AcsEmulator/AcsEmulatorAPI/Migrations/20230216221820_AddEmailPersistence.Designer.cs
AcsEmulator/AcsEmulatorAPI/Migrations/20230216221820_AddEmailPersistence.cs
AcsEmulator/AcsEmulatorAPI/Models/AcsDbContext.cs
AcsEmulator/AcsEmulatorAPI/Models/EmailMessage.cs
AcsEmulator/acs-emulator-ui/src/App.tsx
AcsEmulator/acs-emulator-ui/src/components/EmailMessages.tsx
AcsEmulator/acs-emulator-ui/src/components/LeftNav.tsx
AcsEmulator/acs-emulator-ui/src/services/email.ts

Email persistence

---

TestClients/js/sms/README.md
TestClients/js/sms/package-lock.json
TestClients/js/sms/package.json
TestClients/js/sms/sample.env
TestClients/js/sms/src/listenSmsEvents.ts
TestClients/js/sms/src/sendSms.ts
TestClients/js/sms/src/sendSmsWithOptions.ts
TestClients/js/sms/src/usingAadAuth.ts
TestClients/js/sms/tsconfig.json

* Copied original TS samples from the SDK repo
* Added a new sample for listening to SMS events
TODO: some docs, could probably also move the listener sample into the SDK repo

Add sms test client samples

---

AcsEmulator/AcsEmulatorAPI/CallAutomationController.cs
AcsEmulator/AcsEmulatorAPI/Models/CallAutomationModels.cs
AcsEmulator/AcsEmulatorAPI/Models/CallConnectionProperties.cs
AcsEmulator/AcsEmulatorAPI/Models/ChatModels.cs
AcsEmulator/AcsEmulatorAPI/Models/CommunicationUser.cs
AcsEmulator/AcsEmulatorAPI/Program.cs

Scaffolding the CallAutomationController and the `POST /calling/callConnections` endpoint so others can build on top of it.

Scaffold CallAutomationController

---

AcsEmulator/acs-emulator-ui/src/App.tsx
AcsEmulator/acs-emulator-ui/src/components/Phone.tsx

add mock phone screens with Router

---

AcsEmulator/.gitignore
AcsEmulator/AcsEmulatorAPI/Endpoints/CallAutomation/CallAutomationController.cs
AcsEmulator/AcsEmulatorAPI/Endpoints/CallAutomation/CallAutomationWebSockets.cs
AcsEmulator/AcsEmulatorAPI/Program.cs
AcsEmulator/AcsEmulatorAPI/appsettings.json
AcsEmulator/acs-emulator-ui/package-lock.json
AcsEmulator/acs-emulator-ui/src/components/Phone.tsx

hook up POST callConnections to websocket and display incoming call screen

---

AcsEmulator/AcsEmulatorAPI/Endpoints/CallAutomation/CallAutomationWebSockets.cs
AcsEmulator/AcsEmulatorAPI/Program.cs
AcsEmulator/acs-emulator-ui/src/services/phone.ts

But raising an OnIncomingMessage still doesn't work

Websocket no longer disconnects

---

AcsEmulator/AcsEmulatorAPI.Tests/CallAutomationControllerTests.cs
AcsEmulator/AcsEmulatorAPI/Endpoints/CallAutomation/CallAutomationController.cs
AcsEmulator/AcsEmulatorAPI/Models/CallAutomationModels.cs

Flatten the response object
Result from CA Sample calling emulator:

Flatten the response object of POST /calling/callConnections
